spring:
  profiles:
    include: oauth
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG